language: en-US
reviews:
  profile: chill
  tools:
    prismaLint:
      enabled: true
    luacheck:
      enabled: true
    markdownlint:
      enabled: true
    emberTemplateLint:
      enabled: false
